import Div from "./Div";
import Para from "./Para";
import Span from "./Span";
import Button from "./Button";
import Input from "./Input";
import Header from "./Header";
import Card from "./Cards";
import ProjectCard from "./ProjectCards";
import Carousel from "./Carousel";
import Footer from "./Footer";
import Form from "./ContactForm"; 
import ComingSoon from "./Comingsoon";  
export {Div, Para, Span, Button, Input, Header, Card, ProjectCard, Carousel,  Footer, Form, ComingSoon};